"""Subclass of FrameMarca, which is generated by wxFormBuilder."""

import wx
import guiperfumes
import db

# Implementing FrameMarca
class FrameMarca( guiperfumes.FrameMarca ):
	def __init__( self, parent ):
		guiperfumes.FrameMarca.__init__( self, parent )
		self.atualizarGrid()
	# Handlers for FrameMarca events.
	def adicionarMarca( self, event ):
		nome=self.txtNome.GetValue()
		db.inserirMarca(nome)
		wx.MessageBox(message="Marca Inserida com Sucesso",caption="SysPerfumes",style=wx.OK,parent=self)
		self.atualizarGrid()
	def fecharFrame( self, event ):
		self.Show(False)
	def atualizarMarca( self, event ):
		nome_marca=self.gridMarcas.GetCellValue(event.GetRow(),event.GetCol())
		if (nome_marca):
			id_marca=int(self.gridMarcas.GetCellValue(event.GetRow(),0))
			db.atualizarMarca(id_marca,nome_marca)
			wx.MessageBox(message="Marca Atualizada com Sucesso",caption="SysPerfumes",style=wx.OK,parent=self)
	def atualizarGrid(self):
		if (self.gridMarcas.GetNumberRows()>0):
			self.gridMarcas.DeleteRows(0,self.gridMarcas.GetNumberRows()) #Limpa a tabela
		marcas=db.listarMarca()
		for marca in marcas:
			self.gridMarcas.AppendRows(1)
			self.gridMarcas.SetCellValue(self.gridMarcas.GetNumberRows()-1,0,str(marca[0]))
			self.gridMarcas.SetCellValue(self.gridMarcas.GetNumberRows() - 1, 1, marca[1])
			self.gridMarcas.SetReadOnly(self.gridMarcas.GetNumberRows() - 1, 0, True)




