"""Subclass of FramePerfumesGrid, which is generated by wxFormBuilder."""

import wx
import wx.grid
import guiperfumes
import db

# Implementing FramePerfumesGrid
class FramePerfumesGrid( guiperfumes.FramePerfumesGrid ):
	def __init__( self, parent ):
		guiperfumes.FramePerfumesGrid.__init__( self, parent )

	def adicionarLinha( self, event ):
		self.criarLinha()

	def salvarPerfume( self, event ):
		perfumes=[]
		for i in range(0,self.gridPerfumes.GetNumberRows()):
			perfumes.append([])
			for j in range(0,self.gridPerfumes.GetNumberCols()):
				perfumes[i].append(self.gridPerfumes.GetCellValue(col=j,row=i))
		status,message=db.salvarPerfumes(listaPerfumes=perfumes)
		if status:
			wx.MessageBox(message="Registro(s) Salvo(s) com Sucesso",caption="SysPerfume",style=wx.OK|wx.ICON_INFORMATION)
		else:
			wx.MessageBox(message="Erro ao Salvar Perfumes",caption="SysPerfume",style=wx.OK|wx.ICON_ERROR)
			print(message)

	def exibirTabela(self):
		perfumes=db.listarPerfumes()
		if self.gridPerfumes.GetNumberRows()!=0:
			self.gridPerfumes.DeleteRows(pos=0,numRows=self.gridPerfumes.GetNumberRows())
		for perfume in perfumes:
			self.criarLinha(id_perfume=perfume[0],nome_perfume=perfume[1],quantidade=perfume[2],volume=perfume[3],marca=perfume[4],fixacao=perfume[5])
	def exibirFrame( self, event ):
		self.exibirTabela()
	def criarLinha(self,id_perfume=None,nome_perfume=None,quantidade=None,marca=None,fixacao=None,volume=None):
		self.gridPerfumes.AppendRows(1)
		linha=self.gridPerfumes.GetNumberRows()-1
		self.gridPerfumes.SetReadOnly(linha,0,True)
		self.gridPerfumes.SetCellEditor(linha,2,wx.grid.GridCellNumberEditor(min=1,max=1000))
		self.gridPerfumes.SetCellEditor(linha,3,wx.grid.GridCellChoiceEditor(choices=db.listarVolumeNome()))
		self.gridPerfumes.SetCellEditor(linha, 4,
										wx.grid.GridCellChoiceEditor(choices=db.listarMarcaNome()))
		self.gridPerfumes.SetCellEditor(linha, 5,
										wx.grid.GridCellChoiceEditor(choices=db.listarFixacaoNome()))
		if id_perfume:
			self.gridPerfumes.SetCellValue(linha,0,str(id_perfume))
			self.gridPerfumes.SetCellValue(linha,1, nome_perfume)
			self.gridPerfumes.SetCellValue(linha, 2, str(quantidade))
			self.gridPerfumes.SetCellValue(linha, 3, volume)
			self.gridPerfumes.SetCellValue(linha,4, marca)
			self.gridPerfumes.SetCellValue(linha,5, fixacao)

