"""Subclass of FramePrincipal, which is generated by wxFormBuilder."""

import wx
import guiperfumes
from FrameMarca import FrameMarca
from FrameVolumes import FrameVolumes
from FramePerfumes import FramePerfumes
from FramePerfumesGrid import FramePerfumesGrid
import db

# Implementing FramePrincipal
class FramePrincipal( guiperfumes.FramePrincipal ):

	def __init__( self, parent ):
		guiperfumes.FramePrincipal.__init__( self, parent )
		self.frameMarca = None
		self.frameVolumes=None
		self.framePerfumes=None
	# Handlers for FramePrincipal events.
	def abrirMarca( self, event ):
		if not self.frameMarca:
			self.frameMarca=FrameMarca(self)
		self.frameMarca.Show(True)
	def fecharApp( self, event ):
		# TODO: Implement fecharApp
		pass
	def abrirPerfume( self, event ):
		if not self.framePerfumes:
			#self.framePerfumes=FramePerfumes(self)
			self.framePerfumes=FramePerfumesGrid(self)
		self.framePerfumes.Show(True)
	def abrirVolumes( self, event ):
		if not self.frameVolumes:
			self.frameVolumes=FrameVolumes(self)
		self.frameVolumes.Show(True)
	def fecharFramePrincipal( self, event ):
		db.banco.close()
		self.Destroy()


